[graph]
all-features = true
targets = [
  "aarch64-apple-darwin",
  "x86_64-unknown-linux-gnu",
]

[advisories]
yanked = "deny"

[licenses]
confidence-threshold = 0.93
allow = [
  "Apache-2.0",
  "BSD-3-Clause",
  "CDLA-Permissive-2.0",
  "ISC",
  "MIT",
  "MPL-2.0",
  "Unicode-3.0",
  "WTFPL",
  "Zlib",
]

[[licenses.clarify]]
crate = "language-tokenizer@0.1.0"
expression = "WTFPL"
license-files = [{ path = "LICENSE.md", hash = 0x2915ab65 }]

[[licenses.clarify]]
crate = "mach-sys@0.5.4"
expression = "Apache-2.0"
license-files = [{ path = "LICENSE-APACHE-2.0", hash = 0xb5518783 }]

[bans]
multiple-versions = "allow"
wildcards = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
